### ISSUE TITLE
Mark the Nuget Package as "Unofficial"

### ISSUE THREAD

**Issue by LeeCampbell** [LeeCampbell/HdrHistogram.NET#58]
As this isn't the official HdrHistogram.NET Repo*, we shouldn't be taking the HdrHistogram nuget package title.
It appears to have been taken anyway by the existing thing.
https://www.nuget.org/packages/HdrHistogram.NET/

Also worth removing the build time dependency that has made it into the nuspec file declaration

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <!--TODO: rename to HdrHistogram -->
    <id>HdrHistogram</id>
    <version>2.0.75-beta</version>
    <title>HdrHistogram</title>
    ...
    <tags>HdrHistogram Histogram Instrumentation</tags>
    <!--TODO: remove this build time dependency -->
    <dependencies>
      <dependency id="AssemblyVersion.MSBuild" version="0.1.0" />
    </dependencies>
  </metadata>
</package>
```

*Official one is here - https://github.com/HdrHistogram/HdrHistogram.net

**Comment by LeeCampbell** [comment]
Arguably he can keep the HdrHistogram.NET package, and we can just take HdrHistogram? The .NET seem redundant here. We dont get Rx.NET, we get Rx, right?!

**Comment by LeeCampbell** [comment]
As part of this fix, it seems that the existing tools have just enough friction that we will need to script a bunch of things. 
- The AssemblyVersioning nuget packages currently are not flagged as DevDeps, so try to get added as NugetDependencies to our package.
- We want to ship dll, pdb and xml files from release
- We want to control the versioning of the assembly as Nuget sees it, as .NET sees it and as Windows sees it (all different)
- We will want more control once DNX/UWA and dotnetStandards start rolling out.

I think it is going to be best to follow the lead of the JSON.NET project.

**Comment by peske** [comment]
It's great to see that we'll finally have actively developed supported HdrHistogram port. Thanks for that guyz!
Now question: Nuget package is not available yet, right? Any estimation when it will be published?
Thanks!

**Comment by LeeCampbell** [comment]
I am doing my best to get it out asap. Was hoping to get it out in the
weekend, but was battling build issues.
Should be a matter of days. Would love to get feedback when it is out.

**Comment by LeeCampbell** [comment]
And we have a nuget package! - https://www.nuget.org/packages/HdrHistogram/

Ok so I didn't go with naming it unofficial, but due to the amount of work I have poured into this project, it feels pretty bloody official to me! ;-)
